name: Apply Terraform resources

on:
    push:
      branches:
        - main
        - master
  #workflow_dispatch:
  #  inputs:
  #    dir:
  #      description: "Directory with resources to be applyed"
  #      required: true
  #      default: "env/prod"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  apply-prod:
    name: "terraform apply prod"
    runs-on: ubuntu-latest
    #    env:
    #      MINHA_VAR: "MEU_VALOR"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform -chdir=env/prod fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform -chdir=env/prod init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=env/prod validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=env/prod apply -auto-approve
